# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_limit', models.IntegerField()),
                ('min_limit', models.IntegerField()),
                ('about', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.CharField(default='TBA', max_length=10)),
                ('end_date', models.CharField(default='TBA', max_length=10)),
                ('venue', models.CharField(default='TBA', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.CharField(max_length=2000)),
                ('start_date', models.CharField(default='TBA', max_length=10)),
                ('end_date', models.CharField(default='TBA', max_length=10)),
                ('venue', models.CharField(default='TBA', max_length=40)),
                ('clubdept', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='events.ClubDepartment')),
            ],
        ),
    ]
