# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribere',
            new_name='Subscriber',
        ),
    ]
