# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscribe', '0003_auto_20170426_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='mobile_number',
            field=models.CharField(default='', max_length=13),
        ),
    ]
