# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bhavan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=30)),
                ('vacancy', models.IntegerField()),
                ('bhavan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsoft.Bhavan')),
            ],
        ),
    ]
