# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_auto_20170819_1450'),
        ('regsoft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('two_thousands', models.IntegerField(blank=True, default=0, null=True)),
                ('five_hundreds', models.IntegerField(blank=True, default=0, null=True)),
                ('hundreds', models.IntegerField(blank=True, default=0, null=True)),
                ('fifties', models.IntegerField(blank=True, default=0, null=True)),
                ('twenties', models.IntegerField(blank=True, default=0, null=True)),
                ('tens', models.IntegerField(blank=True, default=0, null=True)),
                ('draft_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('draft_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.TeamCaptain')),
            ],
        ),
    ]
