# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0002_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='captain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrations.TeamCaptain'),
        ),
    ]
