# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0003_auto_20170907_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='time_paid',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
