# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0005_auto_20170910_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='fifties_returned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='five_hundreds_returned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='hundreds_returned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='tens_returned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='twenties_returned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='two_thousands_returned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
