# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0006_auto_20170910_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='coaches_list',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
