# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcaptain',
            name='college',
            field=models.CharField(max_length=100),
        ),
    ]
