# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20170803_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcaptain',
            name='is_single',
            field=models.NullBooleanField(),
        ),
    ]
