# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_groupleader_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcaptain',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
