# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_teamcaptain_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_passengers', models.IntegerField()),
                ('departure', models.CharField(max_length=50)),
                ('arrival', models.CharField(max_length=50)),
                ('g_l', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.GroupLeader')),
            ],
        ),
    ]
