# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20170805_2042'),
        ('registrations', '0007_transport'),
    ]

    operations = [
    ]
