# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_merge_20170806_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupleader',
            name='email_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
