# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-06 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_groupleader_email_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcaptain',
            old_name='controlz_paid',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='teamcaptain',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teamcaptain',
            name='payment_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
