# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_auto_20170807_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='arrival',
        ),
        migrations.AddField(
            model_name='teamcaptain',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teamcaptain',
            name='if_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teamcaptain',
            name='total_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transport',
            name='date',
            field=models.DateTimeField(null=True, max_length=50),
        ),
    ]
