# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_auto_20170812_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcaptain',
            name='pcr_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
