# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_remove_teamcaptain_pcr_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcaptain',
            name='captain',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
