# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_remove_teamcaptain_pcr_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcaptain',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
