# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_auto_20170817_2121'),
        ('registrations', '0019_auto_20170819_1203'),
    ]

    operations = [
    ]
