# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_auto_20170819_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcaptain',
            name='coach',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
