# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0023_auto_20170819_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupleader',
            name='barcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
