# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_groupleader_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcaptain',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
