# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0025_teamcaptain_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='controlz',
            field=models.NullBooleanField(verbose_name='controlz passed'),
        ),
    ]
