# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0026_participant_controlz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='acco',
            field=models.BooleanField(default=False, verbose_name='passed recnacc'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='controlz',
            field=models.BooleanField(default=False, verbose_name='controlz passed'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='firewallz_passed',
            field=models.BooleanField(default=False, verbose_name='passed firewallz_o'),
        ),
    ]
