# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0027_auto_20170906_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcaptain',
            name='extra_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamcaptain',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
