# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0027_auto_20170906_2319'),
        ('registrations', '0027_auto_20170906_2326'),
    ]

    operations = [
    ]
