# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0028_auto_20170907_0434'),
        ('registrations', '0028_merge_20170907_0305'),
    ]

    operations = [
    ]
