# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0004_bill_time_paid'),
        ('registrations', '0030_auto_20170910_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regsoft.Bill'),
        ),
    ]
