# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0031_participant_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='recnacc_time',
            field=models.DateTimeField(null=True),
        ),
    ]
