# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0032_participant_recnacc_time'),
        ('registrations', '0029_merge_20170908_1611'),
    ]

    operations = [
    ]
