# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0033_merge_20170910_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcaptain',
            name='coach_paid',
            field=models.BooleanField(default=False),
        ),
    ]
