# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0034_teamcaptain_coach_paid'),
        ('registrations', '0034_teamcaptain_pcr_final'),
    ]

    operations = [
    ]
