# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0035_merge_20170910_2227'),
        ('registrations', '0035_merge_20170910_2226'),
    ]

    operations = [
    ]
