# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_price'),
        ('registrations', '0037_participant_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('g_l', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.GroupLeader')),
            ],
        ),
    ]
