# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0008_room_capacity'),
        ('registrations', '0038_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='acco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regsoft.Bill'),
        ),
        migrations.AddField(
            model_name='coach',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regsoft.Room'),
        ),
    ]
