# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0039_auto_20170918_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regsoft.Bill'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regsoft.Room'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regsoft.Bill'),
        ),
    ]
