# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-23 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0040_auto_20170918_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='fu_controller',
            field=models.BooleanField(default=False),
        ),
    ]
