# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-23 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0041_participant_fu_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
